script:
  push_to_hub: true
  repo_id: ddp-iitm/biobigbird-further-mimic3-pubmed-abstracts

data:
  streaming: true
  should_load_from_disk: false
  dataset_id: ddp-iitm/pubmed_raw_text_v3

  # ignore if streaming=False
  num_examples: 44816461
  # + 2083179 for mimic3
  # + 42773282 for pubmed abstracts
  # - 40000 for validation

model:
  model_id: ddp-iitm/biobigbird-base-uncased
  tokenizer_id: ddp-iitm/biobigbird-base-uncased
  revision: null
  attention_type: block_sparse
  block_size: 128
  num_random_blocks: 3

data_collator:
  max_length: 1024
  mlm_probability: 0.2

  column_name: text

trainer:
  max_epochs: 5
  batch_size_per_device: 1
  wandb_project_name: biobigbird
  epochs_save_dir: bigbird_base_pubmed_raw_text_v3
  num_save_steps: 20000
  num_eval_steps: 20000
  logging_steps: 8
  max_steps_per_epoch: -1

  dataloader_num_workers: 2
  dataloader_pin_memory: false
  dataloader_prefetch_factor: 8

optax:
  lr: 2.e-5
  init_lr: 1.e-7
  warmup_steps: 5000
  weight_decay: 1.e-2
