data:
  streaming: true
  should_load_from_disk: false
  dataset_id: ddp-iitm/pubmed_raw_text_v3


model:
  model_id: null
  tokenizer_id: ddp-iitm/pubmed_raw_text_v3_tokenizer
  attention_type: block_sparse
  block_size: 128
  num_random_blocks: 3

data_collator:
  max_length: 4096
  mlm_probability: 0.2

  column_name: article

trainer:
  max_epochs: 5
  batch_size_per_device: 2
  wandb_project_name: biobigbird
  epochs_save_dir: model_1st
  logging_steps: 128
  max_steps_per_epoch: -1

  dataloader_num_workers: 2
  dataloader_pin_memory: false
  dataloader_prefetch_factor: 2

optax:
  lr: 5.e-5
  init_lr: 1.e-7
  warmup_steps: 1000
  weight_decay: 1.e-2
