script:
  push_to_hub: true
  repo_id: ddp-iitm/bigbird_base_v4_pubmed_raw_text_v3

data:
  streaming: true
  should_load_from_disk: false
  dataset_id: ddp-iitm/pubmed_raw_text_v3

  # ignore if streaming=False
  num_examples: 2340483

model:
  model_id: ddp-iitm/bigbird_base_v3_pubmed_raw_text_v3
  tokenizer_id: ddp-iitm/bigbird_base_v3_pubmed_raw_text_v3
  revision: 1f3a9f4a511e395f150332b70001f1b76102cf4c
  attention_type: block_sparse
  block_size: 128
  num_random_blocks: 3

data_collator:
  max_length: 4096
  mlm_probability: 0.2

  column_name: text

trainer:
  max_epochs: 5
  batch_size_per_device: 1
  wandb_project_name: biobigbird
  epochs_save_dir: bigbird_base_pubmed_raw_text_v3
  num_save_steps: 20000
  num_eval_steps: 20000
  logging_steps: 8
  max_steps_per_epoch: -1

  dataloader_num_workers: 2
  dataloader_pin_memory: false
  dataloader_prefetch_factor: 8

optax:
  lr: 2.e-5
  init_lr: 1.e-7
  warmup_steps: 5000
  weight_decay: 1.e-2
